### ISSUE TITLE
PNG Verarbeitung

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-backend#128]
Bei PNG-Dateien gibt es beim Erzeugen der `variations` andere Ergebnisse als bei originalen JPG-Dateien:
alle Varianten haben - mit Ausnahme der Thumbnails - die gleiche Größe; vermutlich Ergebnis der Konvertierung nach JPG bei Umwandlung. 

Idealerweise sollten die `variations` auch vom Typ PNG sein (schematische Darstellungen können u.U. durch JPG-Artefakte an Qualität verlieren).

Passiert das alles in deepzoom.py? Ich weiß gar nicht, ob wir dann viel Einfluss drauf haben. Aber das Erzeugen der verschiedenen Formate gab es eigentlich schon lange bevor wir DeepZoom eingeführt haben.

**Comment by chgad** [comment]
Die `variations` haben nichts mit DeepZomm zu tun sondern entstehen durch `django-stdimage` welches NUR für JPEG Dateien vorgesehen ist. Eine implementierung von `django-stdimage`  für PNG Dateien sprengt definitiv des scope für uns.

Ich würde vorschlagen das Dateiformat SVG für schematische Darstellungen zu nutzen. Das ist perdefinition skalierbar (heißt ja ausgeschrieben scaling vector graphics). Um den Upload dieser Dateien zu ermöglichen müssten nur anpassung gemacht werden damit **keine Variationen** und auch **keine DeepZoom Dateien**  erstellt werden.

**Comment by sheepyhollow** [comment]
Ja - tatsächlich sind die Schemata ja auch native SVGs, die PNGs waren nur ein Notnagel. Dann sollte wahrscheinlich das hier 
ganz rausfliegen?

**Comment by chgad** [comment]
Ja das kann man rausnehmen.
