### ISSUE TITLE
Django Admin Session Token & Title

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-backend#129]
I admit, it's pure convenience... 

ist es möglich,
a. ... die Session Tokens (oder was auch immer) so zu trennen, dass man in zwei Django Admin Interfaces gleichzeitig angemeldet sein kann? (wird vor allem bei Vergleichen etc. ermöglicht)
b. ... den App-Titel irgendwo in der Titelleiste anzuzeigen? Oder sogar einen Balken im jeweiligen App-Farbschema?

Falls mal einen Tag Langeweile aufkommt (und es überhaupt möglich ist), wäre es eine Erleichterung für Kerstin und mich.

**Comment by chgad** [comment]
Es sind doch gänzlich unterschiedliche Inhalte; was wollt ihr denn zwischen den Apps vergleichen?

**Comment by sheepyhollow** [comment]
z.T. Staging und Production - aber auch Kerstin arbeitet u.U. parallel in verschiedenen Backends.

**Comment by chgad** [comment]
Der Title muss in jeder App geändert werden, also bitte dort die Issues erstellen.

**Comment by chgad** [comment]
Und den Cross-App-Login würde ich lassen.
Das ist
 1. keine Gängige Praxis in dem Authentication Scheme
 2. steigt Fehleranfälligkeit 
 3. sollte zwischen Staging und Production nicht "verglichen" werden.

**Comment by sheepyhollow** [comment]
Hintergrund für den Cross-App-Login waren vor allem Tests von neuen Sachen im Frontend. Dabei kam es z.B. vor, Slideshows an- und auszuschalten. Aber ist tatsächlich kein Dauerthema, also weg damit.
