### ISSUE TITLE
Categories Title Image

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-backend#130]
Ist es möglich, im Categories-Endpoint ein Image-Feld hinzuzufügen?

Es muss dafür _keinen_ eigenen Bild-Upload geben (wäre ja auch schwierig mit Taggit), sondern es kann automatisch das erstbeste Titelbild einer zugehörigen Slideshow ausgegeben werden.

Dazu müsste allerdings der [Serializer?] in die Slideshows gucken und die Bilder herausfischen.

**Comment by chgad** [comment]
Das lässt sich in Kombination mit #131 erledigen.

**Comment by chgad** [comment]
Nur die thumbnail variation?

**Comment by sheepyhollow** [comment]
Yes please.
