### ISSUE TITLE
Categories active status

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-backend#131]
Aktuell basiert der `categories` endpoint nur auf den Taggit-Tags.

Der `active` Status der Slideshows wird dabei nicht berücksichtigt, so dass es auch zu leeren Categories kommen kann.

Wenn es in einer Category keine aktiven Slideshows gibt sollte die Category nicht im Endpoint angezeigt werdne.

Evtl in Verbindung mit #130 zu lösen?

**Comment by chgad** [comment]
Was passiert mit Kategorien die sowohl aktive als auch inaktive Slideshows enthalten?

**Comment by sheepyhollow** [comment]
Die bleiben drin - um aktiv/inaktiv kümmert sich ja der Slideshow-Endpoint. Inaktive Slideshows sollten dort ja nicht auftauchen.

**Comment by chgad** [comment]
> Die bleiben drin - um aktiv/inaktiv kümmert sich ja der Slideshow-Endpoint. Inaktive Slideshows sollten dort ja nicht auftauchen.

Ne, der Slideshow Enpoint gibt nur die aktiven raus ;) aber gut.

**Comment by sheepyhollow** [comment]
Sagte ich das nicht? Na, so lange klar ist, was wir meinen.
