### ISSUE TITLE
Quiz Erweitern

### ISSUE THREAD

**Issue by chgad** [zentrumnawi/solid-backend#134]
Der Fragentyp `quizquestions` bleibt im Prinzip für alle Fragentypen gleich (`type`, `text`, `difficulty`, `tags`)

#### Das Quiz soll um einen Fragentyp "Ranking" erweitert werden.
 
Neben der normalen Auswertung (stimmt jede Position?) soll eine optionale Auswertung möglich sein, die prüft, ob die Reihenfolge von manchen Items korrekt ist (subsequences).
 
Die Auswertung passiert im Frontend wenn die Option aktiviert ist. Dafür gibt es auch einen extra-Feedback-Text.

- [ ] Answer-Model für `type= RG`:
- text: string (Markdown)
- position: (number)
- [subsequences: (Boolean)]
- feedback_correct: string  (Markdown) 
- feedback_incorrect: string (Markdown
- feedback_subsequences: string (Markdown)

Validierungen
- mindestens 2 answers
- keine doppelten positions
- beim shuffeln der Antworten sollte nicht die korrekte Reihenfolge herauskommen

 #### Das Quiz soll um den einfachen Fragentyp Wahr/Falsch (Simple SC) erweitert werden. 

- [ ] Answer-Model für `type = TF`
- value: boolean
- feedback_correct: string (Markdown)
- feedback_cotext falsch: string (Markdown)

Validierungen
- eine falsche & eine richtige Antwort 

#### Das Quiz _könnte_ noch um einen Fragentyp "Range" erweitert werden.

- [ ] Answer Model für `type = RN` 
- value: number
- range_minimum: number
- range_maximum: number
- tolerance: number
- feedback_correct string (Markdown)
- feedback_incorrect: string (Markdown)

(ggf. können im endpoint alle Zahlenwerte als Array ausgeliefert werden)

Validierungen
- range_minimum < number < range_maximum
- tolerance < range_maximum - range_minimum

**Comment by sheepyhollow** [comment]
Die Zusammenfassung ist hier - soll ich das entsprechend oben im ersten Post anpassen?
https://eplite.studiumdigitale.uni-frankfurt.de/p/ZN-SOLID_Quiz

**Comment by sheepyhollow** [comment]
Ich habe jetzt mal das Issue entsprechend ausformuliert und um die Validierungen ergänzt, die mir eingefallen sind.

Zwei Punkte haben mich aber noch beschäftigt:
1. Bei SC/MC ist ein Feedback correct/incorrect je Antwort sinnvoll. Bei Ranking ist es nur je Frage sinnvoll - wenn wir da aber auch die einzelnen Items in einzelne _answers_ packen - wie lösen wir das mit dem Feedback?
2. Davon abhängig: Die Eigenschaft `subsequences` könnte man auch aus dem Inhalt des Feedbacks abhängig machen. Wenn `feedback_relative == ""` dann wird auch nichts ausgewertet; es müsste dann kein eigenes Boolean-Feld im question model geben.

**Comment by sheepyhollow** [comment]
Gerade gemerkt: Wenn wir "Range" mit einem Slider darstellen, dann spielt ggf. auch die stepsize eine Rolle... z.B. würde bei der Mohs-Skala ein möglicher Wert von 2,5 keinen Sinn ergeben. Sollen wir die als eigene Variable mitgeben oder lässt sich das sinnvoll aus den anderen Zahlen ableiten? Vermutlich müsste man das vorgeben.

**Comment by chgad** [comment]
Ich denke wir bleiben bei einem Answer model und fügen die Felder:

- position: (number)
- [subsequences: (Boolean)]
- feedback_subsequences: string (Markdown)
- value: number
- range_minimum: number
- range_maximum: number
-  tolerance: number


Das Feld  value: boolean für die TF Question ist ja eigentlich durch `correct`abgebildet oder?

Beispiel: Ist ein Elektron ein Fermion?

Antwort 1, text: Ja correct:True
Antwort 2, text: Nein correct: False

@sheepyhollow korrigiere mich wenn ich da jetzt falsch liege... aber das ist doch eigentlich eine Single-Choice Frage mit der limitierung auf 2 ANtworten, oder?

**Comment by sheepyhollow** [comment]
Ja, das ist korrekt - TF ist durch Single-Choice abbildbar. Der Antworttext spielt keine Rolle; wir dachten an explizite Buttons `Wahr` / `Falsch`. Hilfreich wäre aber eine Validierung, die nur zwei answers für TF zulässt, von denen eine richtig und eine falsch sein muss.

**Comment by chgad** [comment]
Also wenn der Text sowieso egal ist, dann reicht ja eine Antwort und zwar die ob die Frage richtig oder falsch ist.

oder?

**Comment by chgad** [comment]
Durch angabe eines Textes könnten wir es den Contentcreator*innen es frei lassen, was in den Buttons steht.

**Comment by sheepyhollow** [comment]
> wenn der Text sowieso egal ist, dann reicht ja eine Antwort
Oh... tatsächlich! Ja klar...

Was die Antworttexte angeht... Es würde die (absichtlich) sehr enge didaktische Zielrichtung des Fragetyps aufbrechen. Ich weiß noch nicht, ob ich das gut finde.  Ich tausche mich nochmal mit Kerstin aus. Aber wir könnten den Default bei wahr/falsch lassen - und wenn ein Text angegeben ist, dann wird der für die Buttons genommen.  Ich tausche mich nochmal mit Kerstin aus.

**Comment by chgad** [comment]
Es ging mir eher un die Situation wie bei der Ansprache im Quiz.

Bertram Bühner ***@***.***> schrieb am Mi., 23. Feb. 2022,
15:08:

**Comment by chgad** [comment]
> beim shuffeln der Antworten sollte nicht die korrekte Reihenfolge herauskommen

Warum nicht? Dydaktisch muss ich doch auch erst überprüfen ob die Reihenfolge nicht vielleicht schon richtig ist?

bzw. Soll der Quizendpoint die Answers immer "Shuffeln" ?

**Comment by sheepyhollow** [comment]
> Dydaktisch muss ich doch auch erst überprüfen ob die Reihenfolge nicht vielleicht schon richtig ist?

True, aber ist schon irgendwie unbefriedigend, wenn ich gar nicht interagieren, sondern nur "ok" klicken muss, oder? :wink:
Aber wenn das die Sache verkompliziert, ist das keine Muss-Anforderung.

Und ja, die Answers sollten immer geshufflet werden, sofern das relevant ist auch bei SC/MC.

**Comment by sheepyhollow** [comment]
Was machen wir mit der stepsize (s.o.)?

**Comment by sheepyhollow** [comment]
Ah, ich nehm's zurück. `range_step` ist im PR #156 drin, alles gut.

**Comment by chgad** [comment]
> Und ja, die Answers sollten immer geshufflet werden, sofern das relevant ist auch bei SC/MC.

Immer shuffeln ist eleganter als nur bei Ausnahme shuffeln ;)

**Comment by sheepyhollow** [comment]
understood! Dann immer shufflen, bitte.
