### ISSUE TITLE
Tags für categories und Inhalte in slideshows

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-backend#139]
Für die Slideshow wären zwei Arten von Tags sinnvoll

1. Für die tatsächlich angezeigten `categories` (siehe auch #130 und #131)
~~2. inhaltliche Tags, um z.B. Slideshows zu einem bestimmten Thema zu filtern~~

**Comment by chgad** [comment]
Inwiefern soll diese "Themen-Tags" in Zukunft genutzt werden?

Mir ist noch nicht der ganz klar was der Nutzen ist SlideShows Thematisch einzuordnen.

**Comment by sheepyhollow** [comment]
Das Thema "2. inhaltliche Tags" ist vorerst vom Tisch. 

Ein Sinn wäre, gezielt nach Schlagworten suchen zu können, die nicht explizit im Titel oder in der Kategorie stehen.

Beispiel: Kategorie "Essen", Slideshow "Frühstück" &rarr; Suche nach Begriff "Aufstrich".

Da das aktuell von keinem Content-/Projektteam als Feature gewünscht ist, müssen wir es auch nicht umsetzen. Es mag aber sein, dass das irgendwann eine Feature Request wird, wenn es wirklich _viele_ Slideshows gibt.

(Eine Suche in Slideshows existiert bislang im Frontend nicht, ist aber geplant - würde dann aber nur in den Slideshow-Titeln und Kategorietiteln suchen i.e. in den Feldern, die auch im slideshow-endpoint zur Verfügung stehen)
