### ISSUE TITLE
Slideshow-Endpoints

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-backend#140]
Für die Slideshows sollte es zwei Endpoints geben

1. Information über alle Slideshows mit ihren Tags und Bildern (siehe #130) ohne pages
2. Aufruf einer einzigen Slideshow mit Inhalt per ID (existiert schon)

Der Slideshow-Übersichts-Endpoint könnte dann z.B. `slideshowinfo` heißen - vielleicht geben wir uns hier eine Konvention über alle Komponenten, so dass das ein konsistentes Schema ist.

**Comment by chgad** [comment]
RESTful ist allerdings 

1. Ein GET auf `/slideshows` --> Alle Slideshows
2. Ein GET auf `/slideshows/<id>`--> SlideShow mit id == <id>

Bis auf das ausschließen der SlideShowPage objekte bei 1. existiert das schon.

**Comment by sheepyhollow** [comment]
Dann RESTful (in allen Komponenten).

**Comment by chgad** [comment]
@sheepyhollow 
> Information über alle Slideshows mit ihren Tags und Bildern (siehe https://github.com/zentrumnawi/solid-backend/issues/130) ohne pages

können wir uns hier einigen dass statt des Inhalts aller pages lediglich die Liste aller zugehörigen ID's mitkommen.

Das entfernen des Key's `pages`suggeriert sonst ein nicht vorhanden sein des Felds bzw. der Relation.

**Comment by sheepyhollow** [comment]
Ja, das passt so!
