### ISSUE TITLE
cross-app tags

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-backend#143]
Es sollte möglich sein, Taggit-Tags zu den Komponenten zu unterscheiden, so dass z.B. nur die in slideshows vergebenen tags abgefragt werden können bzw. die slideshow-tags von anderen tags getrennt werden können.

**Comment by chgad** [comment]
Momentan nutzen wir keine Tags in anderen Apps deshalb low prio.

Wenn wir das angehen:

1. Muss das `Tag`model für alles AUßER den Slideshows benutzt werden
2. Müssen die Slideshows ein eigenes Tag model bekommen
3. Muss der Tag Endpoint in eine eigene app
4. Der Endpoint muss dann über die TaggedItem content_type_id Tags filtern.

Hierbei dürfen die Themen Tags aus #139 nicht vergessen werden.

**Comment by sheepyhollow** [comment]
Ich denke, wir können das wieder schließen.
Es gibt aktuell keinen Bedarf an übergreifenden Tags.
