### ISSUE TITLE
Shuffle Quiz

### ISSUE THREAD

**Issue by chgad** [zentrumnawi/solid-backend#158]
Die Quizantworten sollen "in zufälliger Reihenfolge" ausgegeben werden.

**Comment by chgad** [comment]
@sheepyhollow ich bin aber tatsächlich nicht sicher ob das nicht im Frontend besser aufgehoben wäre.

**Comment by sheepyhollow** [comment]
Filtern im Frontend? Don't tell your backend developer 😈 

Aber ja, das wäre schon okay - wir sollten es nur nicht auf beiden Seiten machen.
Für das Shuffling mit ggf. "Vermeiden der richtigen Reihenfolge" gibt's da auch zwei Leute, die sich da bestimmt gerne Gedanken machen.

**Comment by sheepyhollow** [comment]
Also: Wenn Du eine Umsetzung im Frontend empfiehlst, dann verschieben wir das issue.

**Comment by chgad** [comment]
Ok, also... ich habe gerade echt lange gebraucht um einen vernünftigen Ansatz für "Unordnung" zu finden".
Allgemein ist die Ausgabe Reihenfolge maßgeblich beim Typ "Ranking" wichtig.

Wir gehen mal davon aus,dass jemand bei der Eingabe der QuizAnswers im Backenddiese in der korrekten Reihenfolge eingibt.

Dann shuffeln wir einmal dir Reihenfolge, solte der 1/n! Fall auftreten, dass die Reihnfolge gleichgeblieben ist, geben wir einfach die invertierte Reihenfolge aus.

**Comment by sheepyhollow** [comment]
Das invertieren ist schlau. Ich verstehe aber noch nicht, wofür die Annahme der Reihenfolge notwendig ist - die wird ja durch `position` vorgegeben.

**Comment by chgad** [comment]
Weil die Datenbank nicht nach `position` sortiert.

Bertram Bühner ***@***.***> schrieb am Mi., 2. März 2022,
14:29:

**Comment by sheepyhollow** [comment]
Hm. Wenn dat so is. 

Dann gehen wir mal davon aus, dass das selbst, wenn die Antworten nicht in der richtigen Reihenfolge angegeben werden, nur in einer kleinen Zahl der Fälle zur korrekten Reihung kommt. Das ist ja auch kein Beinbruch.

**Comment by sheepyhollow** [comment]
Ja, passt - vielleicht kann im Admin-Panel ein Hint dazu stehen.
