### ISSUE TITLE
Löschen von Bildern beim

### ISSUE THREAD

**Issue by chgad** [zentrumnawi/solid-backend#31]
Die definierten `ImageField`'s setzen das Feld nur auf `null` wenn man die Clear-Checkbox anklickt. 
Dabei wird die eigentliche Bilddatei nicht gelöscht. Das versucht Datei-Leichen und kann bei gleichnamigem Uploadfile zu seltsamen Dateinamen führen. 

Um das zu lösen gibt es zwei Möglichkeiten:

1. Neue Subclass von `django.models.Model` und überschreiben der save/delete methode.
2. Erstellen einer Reciver Funktion und anbinden an die `post_save` bzw. `post_delete` signale

**Comment by suehtomit** [comment]
Dritte Möglichkeit django-cleanup?
https://pypi.org/project/django-cleanup/

**Comment by suehtomit** [comment]
Mit der Implementierung von django-cleanup ist auch Django selbst upgedated worden auf Verion 3.1a1. Das Django-Admin-Interface hat sich damit leicht verändert.

Dateien werden nun gelöscht, wenn man die Clear-Checkbox anklickt oder eine Instanz löscht, die ein `ImageField` oder `FileField` besitzt. Doch im Fall, wenn eine bestehende Datei, durch eine andere Datei mit demselben Namen ersetzt wird, wird zwar die alte Datei gelöscht, aber die neue ersetzende Datei bekommt einen Namenszusatz.
