### ISSUE TITLE
Quiz model Wahr/Falsch

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-backend#76]
Das Quiz soll um den einfachen Fragentyp Wahr/Falsch (Simple SC) erweitert werden.
Kürzel könnte "TF" sein (True/False)

Model:
- [type: "TF"]
- difficulty (Number)
- Aussagetext (String/Markdown)
- tags (String)
- image (aus image/photograph model)
----
- Wahrheitswert (Boolean)
- Feedbacktext richtig (String/Markdown)
- Feedbacktext falsch (String/Markdown)

**Comment by chgad** [comment]
Siehe #134
