### ISSUE TITLE
Deep Zoom-Option Alphakanal

### ISSUE THREAD

**Issue by suehtomit** [zentrumnawi/solid-backend#86]
- Bei Aktivierung der Deep Zoom-Option kommt es bei Bildern, die einen Alphakanal enthalten, zur Fehlermeldung:
"OSError: cannot write mode RGBA as JPEG".
- Dabei wird der Deep Zoom-Verzeichnisbaum dennoch erstellt, so dass ein weiterer DZI-Erstellungsversuch eine zweite Fehlermeldung auslöst, auch wenn eine Bilddatei mit demselben Namen aber geändertem Format genutzt wird:
"FileExistsError: [Errno 17] File exists: '...'"
- Der Verzeichnisbaum muss dann manuell gelöscht werden.
- Tests durchgeführt mit JP2 (alpha), PNG (alpha), TIFF (alpha).
- Tests mit JPG, JP2, PNG, TIFF verliefen fehlerfrei.
- Die Konvertierung von allen Formaten, auch mit Alphakanal, verläuft bei _django-stdimage (JPEGField)_ allerdings problemlos.

2 Lösungsansätze:

1. Fehler abfangen und DZI-Erstellung für Bilder mit Alphakanal unterbinden, so dass kein Verzeichnisbaum erstellt wird.
2. Konvertierungs-Tool von _stdimage_ auch bei _deepzoom_ anwenden.

**Comment by sheepyhollow** [comment]
Ich denke, das erledigt sich mit Blick auf #128

DeepZoom darf nur JPG enthalten.
