### ISSUE TITLE
Photograph --> MediaObject

### ISSUE THREAD

**Issue by chgad** [zentrumnawi/solid-backend#96]
Momentan ist es in SOLID nur möglich Bilder bzw. Bilder mit Audiodiskreption durch die app `photographs` als Inhalt zur Verfügung zu stellen. Mit diesem Feature Request soll es möglich werden sowhol allein stehende Audio-Dateien als auch Video-Dateien zur Verfügung zu stellen.

ToDo's:
### EDIT:

Es ist sinnvoller vorerst eine neue `media_object` django app zu erstellen und nur die Relation zwischen BaseProfile und Photograph zu ändern. Wir haben momentan nicht die Priorität nochd ie Mittel auch den Wechsel zum MediaObject in den anderen Anwendungsteilen wie Quiz oder SlideShow zu vollziehen.

~~Änderungen des Framings:~~
~~- [ ] Umbennenung der App `photographs/` ---> `media_objects/`~~
~~- [ ] Umbennenung des Model `Photograph` ---> `MediaObject`~~
~~- [ ] Umbenneng der View `PhotographEndpoint` ---> `MediaObjectEndpoint`~~
~~- [ ] Umbennenung des Serializers `PhotographSerializer` ---> `MediaObjectSerializer`~~

~~Änderungen um neu benannten `MediaObject` Model:~~

Erstellen des `MediaObject` Models:

- [x]  Grundlage ist eine Kopie des `Photograph` models
- [x] Neues Feld `media_format` ---> `ChoiceField(("image", "audio", "video"))`
- [x] Feld `img` umbennen zu `file`
- [x] Feld `file`von `JPEGField` ---> Feldklasse die Als `FileField`fungiert für Audio/Video Dateien und als `JPEGField` für 
Bilddateien

~~- [ ] Das `upload_to` wird von `photograph/` zu `media_object` geändert.~~

- [x] Neues Feld `media_duration` für Video/Audio Länge `FloatField()`
- [x] Neues Feld `title` CharField()`

- [x] Datenbank seitig sind die Felder `media_format`, `file`, `author` und `license` die einzigen als `required` zu setzenden Felder

Änderungen um Admininterface:

- [x] Anzeige der `media_format`Auswahl als inline RadioButton
- [x] Permanente anzuzeigen sind die Felder: `medai_format`, `file`,`description`, `title`, `author` und `license`
- [x] Je nach Auswahl von `media_format`sind die Felder:
    - `media_format == image` : `img_original_width`, `img_original_height`, `img_original_scale`, `img_alt`, `audio`, `audio_duration`, `dzi_option`, `dzi_file` und der "World2Pixel Calculator"
    - `media_format in (audio, video)`: `media_duration`
anzuzeigen.

- [x] In der Validierung ist auszuschließen, dass Werte für `media_format == image` eingegeben wurden wenn `media_format in (audio, video)` ausgewählt wurden und umgekehrt.
- [x] die Save methode der AdminFrom ist anzupassen.

### EDIT:

- [x] Erstelle zwietes BaseProfile model ebenfalls als `abstract`, welches statt  der Relation zu `Photograph` eine zu `MediaObject`

hat

- [x]  stelle Migration  ~~ als _gist_~~ im `sample_project`  zur Verfügung um wechsel `Photograph`--> `MediaObject` durchzuführen
- [x] füge `DepreactionWaring` zum "alten" BaseProfile" hinzu. 

Wir gehen bei diesen Änderungen davon aus, dass Audio- und Videodateien in guter Form bereitgestellt werden. Hierbei ist gemeint, dass bspw. Vorschaubilder/Previewthumbnails in den Metadaten der jeweilgen Datei gespeichert sind.

**Comment by sheepyhollow** [comment]
Wir haben heute gemerkt, dass `audio_duration` vom Frontend gar nicht genutzt wird - wir holen uns das direkt aus dem (browser-native) Player. Ich würde sagen, das gilt dann auch mit `media_duration` für Videos.

**Comment by chgad** [comment]
Man könnte es im Frontend auch einfach nutzen statt erneut die Metadaten des Files auszulesen.

**Comment by mkay-sh** [comment]
Warum sollten wir das nochmal seperat implementieren. Das macht das HTML-Audio Element von alleine ;) Weniger Code der gewartet werden muss.

**Comment by chgad** [comment]
Ich hab das auf deine Anregung damals implementiert. Aber gut dann wieder raus damit.

**Comment by sheepyhollow** [comment]
Das ist lange her - da dachten wir wirklich noch, dass wir das brauchen...

**Comment by sheepyhollow** [comment]
Wir können testen, das sieht bislang gut aus!
Allerdings ist das "position"-Feld im Admin-Panel nicht sichtbar/vorhanden, die Anordnung müssen wir aber anpassen können.

Es wäre auch noch gut, wenn die Reihenfolge der Bedienelemente im Admin-Panel umsortiert wird, vor allem sollte die DZI-Checkbox direkt neben `File` stehen und dann direkt der `Alternative Text` (weil _required_).

Sollen wir eine Wunschreihenfolge vorgeben?

**Comment by chgad** [comment]
Wenn ich es nicht erraten soll, ja?

**Comment by sheepyhollow** [comment]
Zwei Punkte habe ich ja schon genannt - aber Liste kommt (bespreche ich mit Kerstin)

**Comment by chgad** [comment]
Ist das noch aktuell?

**Comment by sheepyhollow** [comment]
Habe ich mich neulich auch gefragt - wenn das letzte Ding (Post vom 3.7.) erledigt ist, dann zu damit!

**Comment by chgad** [comment]
Ich weiß nicht ob die Reihnfolge jetzt wie gewünscht ist. Bitte überprüfen!

**Comment by sheepyhollow** [comment]
@kerstinhartmann

**Comment by kerstinhartmann** [comment]
ja, ist erledigt! Die Reihenfolge ist wie damals besprochen.
